/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KdestroyParameters {
  ccname?: string
}
export interface KinitParameters {
  principal: string
  password?: string
  keytab?: string
  realm?: string
  ccname?: string
}
export interface GenerateSpnegoTokenParameters {
  service_principal?: string
  service_fqdn?: string
  hostbased_service?: string
  ccname?: string
}
export declare function kinit(input: KinitParameters): Promise<string>
export declare function kdestroy(input: KdestroyParameters): Promise<void>
export declare function spnego(input: GenerateSpnegoTokenParameters): Promise<string>
